# Generated by Django 3.2.11 on 2022-01-27 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Short title for each resource', max_length=90, unique=True, verbose_name='Short title for resource')),
                ('slug', models.SlugField(default='Auto-generated', unique=True, verbose_name='Resource address')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('visibility', models.CharField(choices=[('public', 'Show to public'), ('private', 'Show to members only.')], default='private', help_text='Control whether guests can see this resource.', max_length=8)),
                ('link_type', models.CharField(choices=[('website', 'Website useful for this style or series.'), ('book', 'Link to page where the book can be purchased'), ('slideshow', 'Slide show of photos or presentation'), ('video', 'Link to video'), ('photo', 'Link to single photo'), ('store', 'Link to the store website'), ('tournament', 'Link to tournament website'), ('none', 'Resource does not have a link')], default='none', help_text='Classification of this link by type for sub-menus.', max_length=20)),
                ('link', models.URLField(blank=True, verbose_name='Link address to be used under the description')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
