# Generated by Django 3.2.11 on 2022-02-07 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import taichi_dfw.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('styles', '0002_members_level'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='TaiChi biography.'),
        ),
        migrations.AddField(
            model_name='user',
            name='biophoto',
            field=models.ImageField(blank=True, default='', upload_to=taichi_dfw.users.models.profile_pic_path),
        ),
        migrations.AddField(
            model_name='user',
            name='cell',
            field=phone_field.models.PhoneField(blank=True, help_text='Number used for text notifications', max_length=31, verbose_name='cell phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='Preferred city for TaiChi meetings.', max_length=30, null=True, verbose_name='City of residence.'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_style',
            field=models.ForeignKey(blank=True, help_text='Select your default TaiChi Style.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='styles.style'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='gmail',
            field=models.EmailField(blank=True, help_text='GMail address, used for authentication.', max_length=200, verbose_name='GMail address'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='leaderFlag',
            field=models.BooleanField(default=False, verbose_name='User is a leader'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='home phone.'),
        ),
        migrations.AddField(
            model_name='user',
            name='resources',
            field=models.ManyToManyField(to='resources.Resource'),
        ),
        migrations.AddField(
            model_name='user',
            name='sponsor',
            field=models.ForeignKey(blank=True, help_text='User who applied leader designation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
