# Generated by Django 3.2.11 on 2022-02-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='level',
            field=models.CharField(choices=[('beginner', 'No experience, just starting out'), ('novice', 'Learning the basics'), ('experienced', 'Learning the details, able to teach'), ('expert', 'Able to do the forms solo and lead'), ('master', 'Acknowledged expert on all of the forms')], default='beginner', help_text='The level of knowledge of the member in this form', max_length=12),
        ),
    ]
